# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-21 05:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='name',
            new_name='car_name',
        ),
    ]
