# Generated by Django 2.0.7 on 2018-07-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbBasicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('industry', models.TextField(blank=True, null=True)),
                ('area', models.TextField(blank=True, null=True)),
                ('pe', models.FloatField(blank=True, null=True)),
                ('outstanding', models.FloatField(blank=True, null=True)),
                ('totals', models.FloatField(blank=True, null=True)),
                ('totalassets', models.FloatField(blank=True, db_column='totalAssets', null=True)),
                ('liquidassets', models.FloatField(blank=True, db_column='liquidAssets', null=True)),
                ('fixedassets', models.FloatField(blank=True, db_column='fixedAssets', null=True)),
                ('reserved', models.FloatField(blank=True, null=True)),
                ('reservedpershare', models.FloatField(blank=True, db_column='reservedPerShare', null=True)),
                ('esp', models.FloatField(blank=True, null=True)),
                ('bvps', models.FloatField(blank=True, null=True)),
                ('pb', models.FloatField(blank=True, null=True)),
                ('timetomarket', models.BigIntegerField(blank=True, db_column='timeToMarket', null=True)),
                ('undp', models.FloatField(blank=True, null=True)),
                ('perundp', models.FloatField(blank=True, null=True)),
                ('rev', models.FloatField(blank=True, null=True)),
                ('profit', models.FloatField(blank=True, null=True)),
                ('gpr', models.FloatField(blank=True, null=True)),
                ('npr', models.FloatField(blank=True, null=True)),
                ('holders', models.FloatField(blank=True, null=True)),
                ('更新日期', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_basic_info',
                'managed': False,
            },
        ),
    ]
